version: "3.3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ad_board
      POSTGRES_USER: ad_board_user
      POSTGRES_PASSWORD: ad_board_pass
    restart: always
  server:
    build: .
    command: python -m app.main
    ports:
      - 9001:9001
    depends_on:
      - db
    restart: always